// AUTO-GENERATED from Real Estate Agent Management Dashboard.xlsx
// Regenerate with: python3 scripts/build-manual-roster.py <path-to-xlsx>
// Snapshot date: 2026-09-01

export const DASHBOARD_SNAPSHOT_DATE = "2026-09-01";

export const ROSTER = [
  {
    "firstName": "Angus Harper",
    "surname": "Sidey",
    "email": "angus.sidey@colliers.com",
    "mobile": "0273185675",
    "dob": "2002-06-08",
    "workAnniversary": "2024-06-13",
    "yearsWithColliers": "2 years, 2 months",
    "yearStartedRE": "2024-06-06",
    "experience": "2 years, 2 months",
    "supervisionLevel": "Level 2",
    "supervisionFrequency": "Quarterly",
    "jobTitle": "Broker",
    "licenceNumber": "20179722",
    "supervisionPlanStart": "2026-07-01",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 6,
    "totalCpdHours": null,
    "licenseExpiry": "2026-06-05",
    "activeListings": null,
    "address": "18 Searells Rd, Strowan, Christchurch 8052, New Zealand"
  },
  {
    "firstName": "Edward William",
    "surname": "Sparrow",
    "email": "edward.sparrow@collierscanterbury.com",
    "mobile": "0272720510",
    "dob": "1969-05-25",
    "workAnniversary": "2025-01-20",
    "yearsWithColliers": "1 years, 7 months",
    "yearStartedRE": "2025-09-23",
    "experience": "0 years, 11 months",
    "supervisionLevel": "Level 2",
    "supervisionFrequency": "Quarterly",
    "jobTitle": "Debt Advisory",
    "licenceNumber": "20199229",
    "supervisionPlanStart": "2026-08-04",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 9,
    "totalCpdHours": null,
    "licenseExpiry": "2026-09-22",
    "activeListings": null,
    "address": "24 Clark St, Sumner, Christchurch 8081, New Zealand"
  },
  {
    "firstName": "Lachlan",
    "surname": "Marshall",
    "email": "lachlan.marshall@collierscanterbury.com",
    "mobile": "0212777123",
    "dob": "2002-07-27",
    "workAnniversary": "2025-02-10",
    "yearsWithColliers": "1 years, 6 months",
    "yearStartedRE": "2025-02-10",
    "experience": "1 years, 6 months",
    "supervisionLevel": "Level 2",
    "supervisionFrequency": "Quarterly",
    "jobTitle": "Broker",
    "licenceNumber": "20198291",
    "supervisionPlanStart": "2026-08-03",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 4,
    "totalCpdHours": null,
    "licenseExpiry": "2026-08-31",
    "activeListings": null,
    "address": "38 McDougall Ave, St Albans, Christchurch 8014, New Zealand"
  },
  {
    "firstName": "Annabelle Brook",
    "surname": "Bramwell",
    "email": "annabelle.bramwell@collierscanterbury.com",
    "mobile": "021 845 885",
    "dob": "1990-03-06",
    "workAnniversary": "2015-08-17",
    "yearsWithColliers": "11 years, 0 months",
    "yearStartedRE": "2016-09-06",
    "experience": "9 years, 11 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "20056993",
    "supervisionPlanStart": "2026-06-29",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 15,
    "totalCpdHours": null,
    "licenseExpiry": "2026-09-05",
    "activeListings": null,
    "address": "20 Larnach Street, Waimari Beach, Christchurch 8083, New Zealand"
  },
  {
    "firstName": "Breanna Marie",
    "surname": "Hodges",
    "email": "breanna.hodges@collierscanterbury.com",
    "mobile": "021 0242 6873",
    "dob": "2001-01-31",
    "workAnniversary": "2020-01-20",
    "yearsWithColliers": "6 years, 7 months",
    "yearStartedRE": "2022-03-23",
    "experience": "4 years, 5 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Executive Assistant",
    "licenceNumber": "20145049 (Suspended)",
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": 0,
    "nonVerifiableHours": 13,
    "totalCpdHours": null,
    "licenseExpiry": "2026-03-22",
    "activeListings": null,
    "address": "26 Cherry Avenue, RD 2, Darfield 7510, New Zealand"
  },
  {
    "firstName": "Christian William",
    "surname": "Kellar",
    "email": "christian.kellar@collierscanterbury.com",
    "mobile": "027 333 4057",
    "dob": "1986-10-02",
    "workAnniversary": "2013-10-31",
    "yearsWithColliers": "12 years, 9 months",
    "yearStartedRE": "2014-01-30",
    "experience": "12 years, 6 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "20014530",
    "supervisionPlanStart": "2026-07-01",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 13,
    "totalCpdHours": null,
    "licenseExpiry": "2026-01-29",
    "activeListings": null,
    "address": "310 Innes Road, Mairehau, Christchurch 8052, New Zealand"
  },
  {
    "firstName": "Elliot Joseph",
    "surname": "Clayton",
    "email": "elliot.clayton@collierscanterbury.com",
    "mobile": "021 774 029",
    "dob": "1990-03-29",
    "workAnniversary": "2018-05-28",
    "yearsWithColliers": "8 years, 2 months",
    "yearStartedRE": "2017-03-01",
    "experience": "9 years, 5 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "20028248",
    "supervisionPlanStart": "2026-07-01",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 13,
    "totalCpdHours": null,
    "licenseExpiry": "2026-02-28",
    "activeListings": null,
    "address": "20 Beveridge Street, Christchurch Central, Christchurch 8013, New Zealand"
  },
  {
    "firstName": "Harry Benjamin",
    "surname": "Peeters",
    "email": "harry.peeters@collierscanterbury.com",
    "mobile": "027 374 1194",
    "dob": "1995-09-15",
    "workAnniversary": "2021-08-12",
    "yearsWithColliers": "5 years, 0 months",
    "yearStartedRE": "2018-11-12",
    "experience": "7 years, 9 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "20090103",
    "supervisionPlanStart": "2026-07-01",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 14,
    "totalCpdHours": null,
    "licenseExpiry": "2026-11-11",
    "activeListings": null,
    "address": "1/2 Canon Street, Edgeware, Christchurch 8014, New Zealand"
  },
  {
    "firstName": "Luke",
    "surname": "Wishnowsky",
    "email": "luke.wishnowsky@collierscanterbury.com",
    "mobile": "021 370 181",
    "dob": "1987-10-21",
    "workAnniversary": "2022-02-14",
    "yearsWithColliers": "4 years, 6 months",
    "yearStartedRE": "2022-02-23",
    "experience": "4 years, 6 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "20141436",
    "supervisionPlanStart": "2026-07-01",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 12,
    "totalCpdHours": null,
    "licenseExpiry": "2026-02-22",
    "activeListings": null,
    "address": "86 Hamilton Avenue, Ilam, Christchurch 8041, New Zealand"
  },
  {
    "firstName": "Marius Damian David",
    "surname": "Ogg",
    "email": "marius.ogg@collierscanterbury.com",
    "mobile": "027 379 9393",
    "dob": "1973-11-22",
    "workAnniversary": "2022-01-17",
    "yearsWithColliers": "4 years, 7 months",
    "yearStartedRE": "2022-02-16",
    "experience": "4 years, 6 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "10013073",
    "supervisionPlanStart": "2026-06-30",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 14,
    "totalCpdHours": null,
    "licenseExpiry": "2026-02-15",
    "activeListings": null,
    "address": "73 Hawford Road, Opawa, Christchurch 8023, New Zealand"
  },
  {
    "firstName": "Michael David Hunter",
    "surname": "Lough",
    "email": "michael.lough@collierscanterbury.com",
    "mobile": "021 030 4270",
    "dob": "1985-10-25",
    "workAnniversary": "2019-05-20",
    "yearsWithColliers": "7 years, 3 months",
    "yearStartedRE": "2019-07-12",
    "experience": "7 years, 1 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "20101869",
    "supervisionPlanStart": "2026-08-04",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 13,
    "totalCpdHours": null,
    "licenseExpiry": "2026-07-11",
    "activeListings": null,
    "address": "83 Edward Avenue, Edgeware, Christchurch 8013, New Zealand"
  },
  {
    "firstName": "Noel Charles",
    "surname": "Gilchrist",
    "email": "noel.gilchrist@collierscanterbury.com",
    "mobile": "021 335 837",
    "dob": "1955-07-13",
    "workAnniversary": "2007-07-02",
    "yearsWithColliers": "19 years, 1 months",
    "yearStartedRE": "2007-07-02",
    "experience": "19 years, 1 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "10009330",
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": 0,
    "nonVerifiableHours": 2,
    "totalCpdHours": null,
    "licenseExpiry": "2026-03-31",
    "activeListings": null,
    "address": "95 Charles Street, Rangiora 7400, New Zealand"
  },
  {
    "firstName": "Oliver",
    "surname": "Salt",
    "email": "oliver.salt@collierscanterbury.com",
    "mobile": "027 838 6494",
    "dob": "1986-10-16",
    "workAnniversary": "2015-01-19",
    "yearsWithColliers": "11 years, 7 months",
    "yearStartedRE": "2015-03-20",
    "experience": "11 years, 5 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "20034974",
    "supervisionPlanStart": "2026-07-01",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 14,
    "totalCpdHours": null,
    "licenseExpiry": "2026-03-19",
    "activeListings": null,
    "address": "37a Totara Street, Fendalton, Christchurch 8041, New Zealand"
  },
  {
    "firstName": "Paul Daryn Howard",
    "surname": "Marshall",
    "email": "paul.marshall@collierscanterbury.com",
    "mobile": "027 221 9994",
    "dob": "1972-07-11",
    "workAnniversary": "2012-10-01",
    "yearsWithColliers": "13 years, 10 months",
    "yearStartedRE": "2012-10-01",
    "experience": "13 years, 10 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "10002308",
    "supervisionPlanStart": "2026-07-02",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 13,
    "totalCpdHours": null,
    "licenseExpiry": "2026-03-31",
    "activeListings": null,
    "address": "116 Fendalton Road, Fendalton, Christchurch 8014, New Zealand"
  },
  {
    "firstName": "Philip Rodney",
    "surname": "Cooper",
    "email": "philip.cooper@collierscanterbury.com",
    "mobile": "021 326 245",
    "dob": "1949-03-02",
    "workAnniversary": "2003-12-01",
    "yearsWithColliers": "22 years, 8 months",
    "yearStartedRE": "2009-11-17",
    "experience": "16 years, 9 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "10010754",
    "supervisionPlanStart": "2026-08-04",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 2,
    "totalCpdHours": null,
    "licenseExpiry": "2026-03-31",
    "activeListings": null,
    "address": "41 Clare Road, St Albans, Christchurch 8014, New Zealand"
  },
  {
    "firstName": "Rory Francis",
    "surname": "McGuigan",
    "email": "rory.mcguigan@collierscanterbury.com",
    "mobile": "021 381 189",
    "dob": "1978-07-05",
    "workAnniversary": "2020-11-02",
    "yearsWithColliers": "5 years, 9 months",
    "yearStartedRE": "2020-09-09",
    "experience": "5 years, 11 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "20118402",
    "supervisionPlanStart": "2026-08-04",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 14,
    "totalCpdHours": null,
    "licenseExpiry": "2026-09-18",
    "activeListings": null,
    "address": "143 Fisher Avenue, Beckenham, Christchurch 8023, New Zealand"
  },
  {
    "firstName": "Thomas Henry",
    "surname": "Lax",
    "email": "tom.lax@collierscanterbury.com",
    "mobile": "027 527 0833",
    "dob": "1988-07-11",
    "workAnniversary": "2018-07-04",
    "yearsWithColliers": "8 years, 1 months",
    "yearStartedRE": "2014-02-12",
    "experience": "12 years, 6 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "20014702",
    "supervisionPlanStart": "2026-07-23",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 14,
    "totalCpdHours": null,
    "licenseExpiry": "2026-02-11",
    "activeListings": null,
    "address": "3 Haughey Drive, Mairehau, Christchurch 8052, New Zealand"
  },
  {
    "firstName": "William",
    "surname": "Franks",
    "email": "will.franks@collierscanterbury.com",
    "mobile": "027 250 0130",
    "dob": "1989-06-26",
    "workAnniversary": "2013-03-04",
    "yearsWithColliers": "13 years, 5 months",
    "yearStartedRE": "2013-09-26",
    "experience": "12 years, 10 months",
    "supervisionLevel": "Level 4",
    "supervisionFrequency": "Half Yearly",
    "jobTitle": "Broker",
    "licenceNumber": "20012970",
    "supervisionPlanStart": "2026-06-30",
    "reviewDate": "2026-12-01",
    "verifiableHours": 10,
    "nonVerifiableHours": 13,
    "totalCpdHours": null,
    "licenseExpiry": "2026-10-31",
    "activeListings": null,
    "address": "3/388 Montreal Street, Christchurch Central, Christchurch 8013, New Zealand"
  },
  {
    "firstName": "Anna Kay",
    "surname": "Small",
    "email": "anna.small@collierscanterbury.com",
    "mobile": "027 927 5337",
    "dob": "1982-10-07",
    "workAnniversary": "2022-04-26",
    "yearsWithColliers": "4 years, 3 months",
    "yearStartedRE": null,
    "experience": null,
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Executive Assistant",
    "licenceNumber": null,
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": null,
    "nonVerifiableHours": null,
    "totalCpdHours": null,
    "licenseExpiry": null,
    "activeListings": null,
    "address": "9 Argo Place, Casebrook, Christchurch 8051, New Zealand"
  },
  {
    "firstName": "Benjamin Stewart",
    "surname": "Cameron",
    "email": "ben.cameron@collierscanterbury.com",
    "mobile": "0211073540",
    "dob": "1983-03-29",
    "workAnniversary": "2025-04-21",
    "yearsWithColliers": "1 years, 4 months",
    "yearStartedRE": "2025-01-22",
    "experience": "1 years, 7 months",
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Broker",
    "licenceNumber": "20014294",
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": 10,
    "nonVerifiableHours": 13,
    "totalCpdHours": null,
    "licenseExpiry": "2026-01-21",
    "activeListings": null,
    "address": "18 Waiau St, Cracroft, Christchurch 8025, New Zealand"
  },
  {
    "firstName": "Brynn James",
    "surname": "Burrows",
    "email": "brynn.burrows@collierscanterbury.com",
    "mobile": "021 375 917",
    "dob": "1975-08-17",
    "workAnniversary": "2015-04-13",
    "yearsWithColliers": "11 years, 4 months",
    "yearStartedRE": "2009-11-17",
    "experience": "16 years, 9 months",
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Director/Broker",
    "licenceNumber": "10004101",
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": 10,
    "nonVerifiableHours": 10,
    "totalCpdHours": null,
    "licenseExpiry": "2026-03-31",
    "activeListings": null,
    "address": "19 Morgans Valley, Christchurch, Christchurch 8022, New Zealand"
  },
  {
    "firstName": "Caitlin",
    "surname": "Knudsen",
    "email": "caitlin.knudsen@collierscanterbury.com",
    "mobile": "027 850 6623",
    "dob": "2002-04-23",
    "workAnniversary": "2026-04-13",
    "yearsWithColliers": "0 years, 4 months",
    "yearStartedRE": null,
    "experience": null,
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Marketing Executive",
    "licenceNumber": null,
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": null,
    "nonVerifiableHours": null,
    "totalCpdHours": null,
    "licenseExpiry": null,
    "activeListings": null,
    "address": "14 Speight St, Mairehau, Christchurch 8013, New Zealand"
  },
  {
    "firstName": "Courtney Rachael",
    "surname": "Doig",
    "email": "courtney.doig@collierscanterbury.com",
    "mobile": "021 991 251",
    "dob": "1987-08-15",
    "workAnniversary": "2011-05-02",
    "yearsWithColliers": "15 years, 3 months",
    "yearStartedRE": "2019-02-01",
    "experience": "7 years, 6 months",
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Broker",
    "licenceNumber": "20013797",
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": 10,
    "nonVerifiableHours": 21,
    "totalCpdHours": null,
    "licenseExpiry": "2026-01-31",
    "activeListings": null,
    "address": "24 Head Street, Sumner, Christchurch 8081, New Zealand"
  },
  {
    "firstName": "Esha Sofia",
    "surname": "McCallion",
    "email": "esha.mccallion@collierscanterbury.com",
    "mobile": "02102940491",
    "dob": "2026-10-28",
    "workAnniversary": "2025-06-30",
    "yearsWithColliers": "1 years, 1 months",
    "yearStartedRE": null,
    "experience": null,
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Broker Support",
    "licenceNumber": null,
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": null,
    "nonVerifiableHours": null,
    "totalCpdHours": null,
    "licenseExpiry": null,
    "activeListings": null,
    "address": null
  },
  {
    "firstName": "Hamish Paul",
    "surname": "Doig",
    "email": "hamish.doig@collierscanterbury.com",
    "mobile": "021 320 149",
    "dob": "1956-08-12",
    "workAnniversary": "2002-05-01",
    "yearsWithColliers": "24 years, 3 months",
    "yearStartedRE": "2010-03-12",
    "experience": "16 years, 5 months",
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Managing Director",
    "licenceNumber": "10017522",
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": 10,
    "nonVerifiableHours": 13,
    "totalCpdHours": null,
    "licenseExpiry": "2026-03-31",
    "activeListings": null,
    "address": "70 Scarborough Road, Scarborough, Christchurch 8081, New Zealand"
  },
  {
    "firstName": "Hayley Rose",
    "surname": "Band",
    "email": "hayley.band@collierscanterbury.com",
    "mobile": "0276300801",
    "dob": "2001-08-30",
    "workAnniversary": "2025-05-26",
    "yearsWithColliers": "1 years, 2 months",
    "yearStartedRE": null,
    "experience": null,
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Broker Support",
    "licenceNumber": null,
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": null,
    "nonVerifiableHours": null,
    "totalCpdHours": null,
    "licenseExpiry": null,
    "activeListings": null,
    "address": "812 Mill Rd, Ohoka 7475, New Zealand"
  },
  {
    "firstName": "Jason Richard",
    "surname": "Wills",
    "email": "jason.wills@collierscanterbury.com",
    "mobile": "0274351491",
    "dob": "1972-01-08",
    "workAnniversary": "2026-05-11",
    "yearsWithColliers": "0 years, 3 months",
    "yearStartedRE": "2019-01-16",
    "experience": "7 years, 7 months",
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Chief Operating Officer",
    "licenceNumber": "10011965",
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": 10,
    "nonVerifiableHours": 12.5,
    "totalCpdHours": 11.5,
    "licenseExpiry": "2026-12-31",
    "activeListings": null,
    "address": "15 Wardell St, Wigram, Christchurch 8042, New Zealand"
  },
  {
    "firstName": "Karen",
    "surname": "Doig",
    "email": "karendoig@xtra.co.nz",
    "mobile": "021 529 561",
    "dob": "1957-11-05",
    "workAnniversary": "2002-05-01",
    "yearsWithColliers": "24 years, 3 months",
    "yearStartedRE": null,
    "experience": null,
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Director",
    "licenceNumber": null,
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": null,
    "nonVerifiableHours": null,
    "totalCpdHours": null,
    "licenseExpiry": null,
    "activeListings": null,
    "address": "70 Scarborough Road, Scarborough, Christchurch 8081, New Zealand"
  },
  {
    "firstName": "Maree Anne",
    "surname": "Crocker",
    "email": "maree.crocker@collierscanterbury.com",
    "mobile": "027 271 5726",
    "dob": "1966-06-15",
    "workAnniversary": "2007-10-15",
    "yearsWithColliers": "18 years, 10 months",
    "yearStartedRE": null,
    "experience": null,
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Financial Controller",
    "licenceNumber": null,
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": null,
    "nonVerifiableHours": null,
    "totalCpdHours": null,
    "licenseExpiry": null,
    "activeListings": null,
    "address": "230b Lake Terrace Road, Shirley, Christchurch 8061, New Zealand"
  },
  {
    "firstName": "Mark James Gordon",
    "surname": "Macauley",
    "email": "mark.macauley@collierscanterbury.com",
    "mobile": "021 650 460",
    "dob": "1975-02-13",
    "workAnniversary": "2015-03-17",
    "yearsWithColliers": "11 years, 5 months",
    "yearStartedRE": "2009-11-17",
    "experience": "16 years, 9 months",
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "General Manager",
    "licenceNumber": "10007995",
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": 10,
    "nonVerifiableHours": 20,
    "totalCpdHours": null,
    "licenseExpiry": "2026-03-31",
    "activeListings": null,
    "address": "72 Glandovey Road, Fendalton, Christchurch 8052, New Zealand"
  },
  {
    "firstName": "Mia",
    "surname": "Fyall",
    "email": "mia.fyall@collierscanterbury.com",
    "mobile": "0274676024",
    "dob": "2004-11-27",
    "workAnniversary": "2024-03-04",
    "yearsWithColliers": "2 years, 5 months",
    "yearStartedRE": null,
    "experience": null,
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Receptionist",
    "licenceNumber": null,
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": null,
    "nonVerifiableHours": null,
    "totalCpdHours": null,
    "licenseExpiry": null,
    "activeListings": null,
    "address": "46D Liffeyfields Dr, Lincoln 7608, New Zealand"
  },
  {
    "firstName": "Nicholas Karl",
    "surname": "Doig",
    "email": "nick.doig@collierscanterbury.com",
    "mobile": "021 944 722",
    "dob": "1984-09-03",
    "workAnniversary": "2003-02-05",
    "yearsWithColliers": "23 years, 6 months",
    "yearStartedRE": "2019-02-05",
    "experience": "7 years, 6 months",
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Director/Broker",
    "licenceNumber": "10005637",
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": 10,
    "nonVerifiableHours": 14,
    "totalCpdHours": null,
    "licenseExpiry": "2026-03-31",
    "activeListings": null,
    "address": "94 Sumnervale Drive, Sumner, Christchurch, Christchurch 8081, New Zealand"
  },
  {
    "firstName": "Sam Jeffrey",
    "surname": "Staite",
    "email": "sam.staite@collierscanterbury.com",
    "mobile": "021 738 245",
    "dob": "1985-06-19",
    "workAnniversary": "2015-03-23",
    "yearsWithColliers": "11 years, 5 months",
    "yearStartedRE": "2009-11-17",
    "experience": "16 years, 9 months",
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Director/Broker",
    "licenceNumber": "10013218",
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": 10,
    "nonVerifiableHours": 9,
    "totalCpdHours": null,
    "licenseExpiry": "2026-03-31",
    "activeListings": null,
    "address": "54 Weka St, Fendalton, Christchurch 8041, New Zealand"
  },
  {
    "firstName": "Sarah",
    "surname": "McQuilkin",
    "email": "sarah.mcquilkin@collierscanterbury.com",
    "mobile": "0277570500",
    "dob": "1993-11-18",
    "workAnniversary": "2023-03-06",
    "yearsWithColliers": "3 years, 5 months",
    "yearStartedRE": null,
    "experience": null,
    "supervisionLevel": null,
    "supervisionFrequency": null,
    "jobTitle": "Marketing Executive",
    "licenceNumber": null,
    "supervisionPlanStart": null,
    "reviewDate": null,
    "verifiableHours": null,
    "nonVerifiableHours": null,
    "totalCpdHours": null,
    "licenseExpiry": null,
    "activeListings": null,
    "address": "25 Bailey St, Templeton, Christchurch 8040, New Zealand"
  }
];

export const BROKER_CONTRACT_AUDITS = [
  {
    "firstName": "Angus Harper",
    "surname": "Sidey",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Lachlan",
    "surname": "Marshall",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Annabelle Brook",
    "surname": "Bramwell",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Christian William",
    "surname": "Kellar",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Elliot Joseph",
    "surname": "Clayton",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Harry Benjamin",
    "surname": "Peeters",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Luke",
    "surname": "Wishnowsky",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Marius Damian David",
    "surname": "Ogg",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Michael David Hunter",
    "surname": "Lough",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Noel Charles",
    "surname": "Gilchrist",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Oliver",
    "surname": "Salt",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Paul Daryn Howard",
    "surname": "Marshall",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Philip Rodney",
    "surname": "Cooper",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Rory Francis",
    "surname": "McGuigan",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Thomas Henry",
    "surname": "Lax",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "William",
    "surname": "Franks",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Benjamin Stewart",
    "surname": "Cameron",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Brynn James",
    "surname": "Burrows",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Courtney Rachael",
    "surname": "Doig",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Nicholas Karl",
    "surname": "Doig",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  },
  {
    "firstName": "Sam Jeffrey",
    "surname": "Staite",
    "issuesIdentified": null,
    "trainingGiven": null,
    "comments": null
  }
];

export const OPEN_ISSUES_REGISTER = [
  {
    "Priority": 3,
    "Category": null,
    "Issue/Opportunity Description": "Project Trail type of system - Anna started looking into teams - to help manage projects like Mark & Mo working togetther on tasks - status and who is doing what",
    "Impact (High/Medium/Low)": "Medium",
    "Urgency (High/Medium/Low)": "Low",
    "Status": "Underway",
    "Owner": "Anna/Jase",
    "Proposed Action/Resolution": "Waiting on Manux to come back to Anna. JW to check what Anna needs as JW has admin access to microsoft tenant",
    "Target Date": null,
    "Notes": "Mark idea"
  },
  {
    "Priority": 1,
    "Category": null,
    "Issue/Opportunity Description": "IT project to look at consolidating all our systems into one stop shop ",
    "Impact (High/Medium/Low)": "High",
    "Urgency (High/Medium/Low)": "Medium",
    "Status": "Underway",
    "Owner": "Jason",
    "Proposed Action/Resolution": "Design Scope Drafted and ready to go to RFP once Mark happy with scope. - Side projects completed; PropCMA complete; Sales deal sheet complete; lease deal sheet underway - Waiting on Mark",
    "Target Date": null,
    "Notes": "JW idea"
  },
  {
    "Priority": 1,
    "Category": "Risk",
    "Issue/Opportunity Description": "Supervision of agents",
    "Impact (High/Medium/Low)": "High",
    "Urgency (High/Medium/Low)": "High",
    "Status": "Underway",
    "Owner": "Jason",
    "Proposed Action/Resolution": "First round 95% complete - Just waiting to meet with Noel - Still waiting on Noel to come back to me. Last reminder sent 25/8/26",
    "Target Date": null,
    "Notes": "Monitor quarterly"
  },
  {
    "Priority": 2,
    "Category": null,
    "Issue/Opportunity Description": "Create a pipeline system that we could use across all our sales meetings run by the EA's - Look at using our existing sales meeting sheets - find out where the EA's pull that information from, then create the pipeline using AI",
    "Impact (High/Medium/Low)": "High",
    "Urgency (High/Medium/Low)": "Low",
    "Status": "Underway",
    "Owner": "Jase",
    "Proposed Action/Resolution": "First draft complete to show Mark. Hayely will kick off once Mark happy with look and function. Showed Sam and Nick and made changes for their teams. Working with Esha and Bree to finalise using the system across all teams.",
    "Target Date": null,
    "Notes": "Mark idea"
  },
  {
    "Priority": null,
    "Category": null,
    "Issue/Opportunity Description": "PropCMA Project - Streamline the Appraisal & IM Process - Use a focus group with a couple of brokers, Bree & Sarah",
    "Impact (High/Medium/Low)": "High",
    "Urgency (High/Medium/Low)": "Low",
    "Status": "Underway",
    "Owner": "Jason",
    "Proposed Action/Resolution": "Changing this to work on the $1m to $4m appraisals - Turns out every proposal is bespoke so will stick with the basic CMA report. Waiting on the EA's or a student to update the existing data fields such as yield, rental income.",
    "Target Date": null,
    "Notes": "Mark's idea"
  },
  {
    "Priority": null,
    "Category": null,
    "Issue/Opportunity Description": "AI policy and lockdown for team",
    "Impact (High/Medium/Low)": "High",
    "Urgency (High/Medium/Low)": "Medium",
    "Status": "Underway",
    "Owner": "Jason",
    "Proposed Action/Resolution": "Manux are installing MS defender for cloud apps on our network so they can monitor what the team are using and lock down potential risks using AI tools. They also need to audit our users permissions to see what they can access on our network. We don't want copilot to let them see our admin files etc. Price from Manux $49.56 per user per month. approx $1,486 p.m.",
    "Target Date": null,
    "Notes": "Note: Colliers (Global) are going with copilot and gemini professional. They have create helpful copilit prompts in the hub and also helpful how to videos that we could leverage off"
  },
  {
    "Priority": null,
    "Category": "Quick Win",
    "Issue/Opportunity Description": "Create list of all our suppliers and partners to check where our contracts are at and if there is an opportunity for sponsorship and better pricing",
    "Impact (High/Medium/Low)": "Low",
    "Urgency (High/Medium/Low)": "Low",
    "Status": "Open",
    "Owner": "Jason",
    "Proposed Action/Resolution": "See Anna for a list of our suppliers and partners. Meet with each of them to check on relationship and opportunites for sponsorship",
    "Target Date": null,
    "Notes": "Feedback stage"
  },
  {
    "Priority": null,
    "Category": "Quick Win",
    "Issue/Opportunity Description": "Optimize team meeting schedule",
    "Impact (High/Medium/Low)": "Low",
    "Urgency (High/Medium/Low)": "Medium",
    "Status": "Open",
    "Owner": "Jason",
    "Proposed Action/Resolution": "Consolidate updates into a shared dashboard to reduce meeting frequency",
    "Target Date": null,
    "Notes": "Feedback stage"
  },
  {
    "Priority": null,
    "Category": null,
    "Issue/Opportunity Description": "JW to meet casually with brokers for coffee to find out what's going well, what's not and what can we do better",
    "Impact (High/Medium/Low)": "High",
    "Urgency (High/Medium/Low)": "Low",
    "Status": "Open",
    "Owner": "Jason",
    "Proposed Action/Resolution": null,
    "Target Date": null,
    "Notes": null
  },
  {
    "Priority": null,
    "Category": null,
    "Issue/Opportunity Description": "Winter / Summer Promotions - Would this work for commercial? Advertising Deals",
    "Impact (High/Medium/Low)": null,
    "Urgency (High/Medium/Low)": null,
    "Status": "Open",
    "Owner": null,
    "Proposed Action/Resolution": null,
    "Target Date": null,
    "Notes": null
  },
  {
    "Priority": null,
    "Category": null,
    "Issue/Opportunity Description": "New process to monitor our campaign wins & losses. JW to call up the clients we missed out on to see if there was anything we could do better in the future",
    "Impact (High/Medium/Low)": "High",
    "Urgency (High/Medium/Low)": "Low",
    "Status": "Open",
    "Owner": "Jason",
    "Proposed Action/Resolution": null,
    "Target Date": null,
    "Notes": "Mark's idea"
  },
  {
    "Priority": null,
    "Category": null,
    "Issue/Opportunity Description": "Business Plan session to target new areas of business for Colliers - Jw to lead the session",
    "Impact (High/Medium/Low)": null,
    "Urgency (High/Medium/Low)": null,
    "Status": "Open",
    "Owner": null,
    "Proposed Action/Resolution": null,
    "Target Date": null,
    "Notes": null
  },
  {
    "Priority": null,
    "Category": null,
    "Issue/Opportunity Description": "Creating a new online process for the dealsheets to be automated from the EA's to accounts, and once processed the deal updates the propCMA system",
    "Impact (High/Medium/Low)": "High",
    "Urgency (High/Medium/Low)": "Low",
    "Status": "CLOSED",
    "Owner": null,
    "Proposed Action/Resolution": null,
    "Target Date": null,
    "Notes": "JW idea"
  },
  {
    "Priority": null,
    "Category": null,
    "Issue/Opportunity Description": "Operations manual - turn this into a searchable website",
    "Impact (High/Medium/Low)": "Low",
    "Urgency (High/Medium/Low)": "Low",
    "Status": "CLOSED",
    "Owner": null,
    "Proposed Action/Resolution": "Ongoing updates to keep up to date",
    "Target Date": null,
    "Notes": null
  },
  {
    "Priority": null,
    "Category": "Risk",
    "Issue/Opportunity Description": "REA verifiable & NV training process",
    "Impact (High/Medium/Low)": "High",
    "Urgency (High/Medium/Low)": "High",
    "Status": "CLOSED",
    "Owner": "Jason",
    "Proposed Action/Resolution": "Audit all the training logs for the agents and find out the status of everyone both NV & V. Also note the expiry date of agents license and implement reminder system",
    "Target Date": null,
    "Notes": "Monitor monthly"
  },
  {
    "Priority": null,
    "Category": "Quick Win",
    "Issue/Opportunity Description": "Automate weekly status reporting",
    "Impact (High/Medium/Low)": "Medium",
    "Urgency (High/Medium/Low)": "Low",
    "Status": "CLOSED",
    "Owner": "Jason",
    "Proposed Action/Resolution": "Implement master spreadsheet to colate all information ",
    "Target Date": null,
    "Notes": "Done"
  },
  {
    "Priority": null,
    "Category": null,
    "Issue/Opportunity Description": "Register for the REINZ awards - Check with Maree to see who would qualify",
    "Impact (High/Medium/Low)": null,
    "Urgency (High/Medium/Low)": null,
    "Status": "CLOSED",
    "Owner": null,
    "Proposed Action/Resolution": null,
    "Target Date": null,
    "Notes": null
  },
  {
    "Priority": null,
    "Category": null,
    "Issue/Opportunity Description": "Recruit financial controller - Ad going up today",
    "Impact (High/Medium/Low)": null,
    "Urgency (High/Medium/Low)": null,
    "Status": "CLOSED",
    "Owner": null,
    "Proposed Action/Resolution": "Last meeting with Hamish and Mark Wednesday 17 June",
    "Target Date": null,
    "Notes": null
  },
  {
    "Priority": null,
    "Category": null,
    "Issue/Opportunity Description": "Auction Brought Forward / Pre Auction Offer Process",
    "Impact (High/Medium/Low)": null,
    "Urgency (High/Medium/Low)": null,
    "Status": "CLOSED",
    "Owner": null,
    "Proposed Action/Resolution": "Underway",
    "Target Date": null,
    "Notes": null
  }
];

export const SUPPLIERS_SPONSORS = [
  {
    "Service/Product Provided": "IT Support",
    "Company Name": "Manux Solutions",
    "Contact Person": "Jonathon Garrett",
    "Email Address": "jgarrett@manux.nz",
    "Phone Number": "021 332 954 ",
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": "Pay-per-incident ?",
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Internet / Cloud Infrastructure",
    "Company Name": null,
    "Contact Person": null,
    "Email Address": null,
    "Phone Number": null,
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Photocopiers/Printers",
    "Company Name": "Heartland",
    "Contact Person": "Daryl Young",
    "Email Address": null,
    "Phone Number": 274855811,
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "REA Trainer",
    "Company Name": "Palfreyman Ltd",
    "Contact Person": "David Palfreyman",
    "Email Address": "info@davidpalfreyman.co.nz",
    "Phone Number": "+64 21 51 7272",
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Portals",
    "Company Name": "Trademe",
    "Contact Person": "David Tudehope",
    "Email Address": "david.tudehope@trademe.co.nz",
    "Phone Number": 212462661,
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Portals",
    "Company Name": "Oneroof",
    "Contact Person": "Mitch Crowe",
    "Email Address": "mitch.crowe@nzme.co.nz",
    "Phone Number": 272435930,
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Portals",
    "Company Name": "realestate.co.nz",
    "Contact Person": null,
    "Email Address": null,
    "Phone Number": null,
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Portals",
    "Company Name": "Hougarden",
    "Contact Person": null,
    "Email Address": null,
    "Phone Number": null,
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Website Provider",
    "Company Name": null,
    "Contact Person": null,
    "Email Address": null,
    "Phone Number": null,
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Lead Generation",
    "Company Name": null,
    "Contact Person": null,
    "Email Address": null,
    "Phone Number": null,
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Marketing Services",
    "Company Name": "Campaign Track",
    "Contact Person": "Our Sarah manages",
    "Email Address": null,
    "Phone Number": null,
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Franchisor",
    "Company Name": "Colliers International",
    "Contact Person": null,
    "Email Address": null,
    "Phone Number": null,
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Advertising",
    "Company Name": "Stuff",
    "Contact Person": "Alicia Peebles",
    "Email Address": "Alicia.peebles@stuff.co.nz",
    "Phone Number": null,
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Photographers",
    "Company Name": "Open2View",
    "Contact Person": "David Young",
    "Email Address": "david.young@open2view.com",
    "Phone Number": 273409570,
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": "Complaints / Insurance",
    "Company Name": "BMS Risk Solutions",
    "Contact Person": "Helen Hastie",
    "Email Address": "helen.hastie@bmsrisk.com",
    "Phone Number": "027 3566 869 ",
    "Type (Supplier/Partner)": null,
    "Contract Start Date": null,
    "Contract Expiry Date": null,
    "Renewal Notice Period": null,
    "Contract Value": null,
    "Payment Terms": null,
    "Status (Active/Pending/Expired)": null,
    "Notes": null
  },
  {
    "Service/Product Provided": null,
    "Company Name": "Example Solutions Ltd",
    "Contact Person": "Jane Smith",
    "Email Address": "jane.smith@example.com",
    "Phone Number": "+64 3-123-4567",
    "Type (Supplier/Partner)": "Supplier",
    "Contract Start Date": "2025-01-01 00:00:00",
    "Contract Expiry Date": "2026-01-01 00:00:00",
    "Renewal Notice Period": "90 Days",
    "Contract Value": "$12000/yr",
    "Payment Terms": "Net 30",
    "Status (Active/Pending/Expired)": "Active",
    "Notes": "Annual license for core hosting services. Review for price adjustment in Oct."
  },
  {
    "Service/Product Provided": null,
    "Company Name": "Creative Media Works",
    "Contact Person": "Sarah Wilson",
    "Email Address": "sarah@creativemedia.co.nz",
    "Phone Number": "+64 4-555-0199",
    "Type (Supplier/Partner)": "Supplier",
    "Contract Start Date": "2025-03-01 00:00:00",
    "Contract Expiry Date": "2026-03-01 00:00:00",
    "Renewal Notice Period": "30 Days",
    "Contract Value": "$2500/mo",
    "Payment Terms": "Monthly",
    "Status (Active/Pending/Expired)": "Active",
    "Notes": "Retainer for social media management and ad creative."
  },
  {
    "Service/Product Provided": null,
    "Company Name": "Standard Tech Support",
    "Contact Person": "Support Team",
    "Email Address": "help@standardtech.io",
    "Phone Number": "+1 800-555-0123",
    "Type (Supplier/Partner)": "Supplier",
    "Contract Start Date": "2024-11-01 00:00:00",
    "Contract Expiry Date": "2025-11-01 00:00:00",
    "Renewal Notice Period": "None",
    "Contract Value": "Pay-per-incident",
    "Payment Terms": "Immediate",
    "Status (Active/Pending/Expired)": "Active",
    "Notes": "On-call support for hardware issues. No fixed expiry but review performance annually."
  },
  {
    "Service/Product Provided": null,
    "Company Name": "Strategic Alliances Inc",
    "Contact Person": "Mark Thompson",
    "Email Address": "mark@strategic-inc.com",
    "Phone Number": "+61 2-9876-5432",
    "Type (Supplier/Partner)": "Partner",
    "Contract Start Date": "2025-02-10 00:00:00",
    "Contract Expiry Date": "2027-02-10 00:00:00",
    "Renewal Notice Period": "120 Days",
    "Contract Value": "Commission",
    "Payment Terms": "Quarterly",
    "Status (Active/Pending/Expired)": "Active",
    "Notes": "Mutual referral agreement. Contract includes exclusivity clause in AU/NZ markets."
  }
];

export const REINZ_AWARDS = {
  "note": "Maree is collating the information for these awards. Anna is registering our Sam and our office for these two awards. Mark feels we won't have big enough deals to win the Deal of the Year awards.",
  "categories": [
    "Individual Commercial & Industrial Salesperson of the Year",
    "Commercial & Industrial Office of the Year \u2013 Medium",
    "New Sales Deal of the Year \u2014 recognises a single, completed commercial or industrial property transaction. Eligible transactions are assessed on settlement date and verified by an independent auditor.",
    "New Commercial Leasing Deal of the Year \u2014 recognises a single completed commercial property leasing transaction that demonstrates scale and commercial value. Qualifying lease deals are verified by an independent auditor."
  ]
};

export const SUPERVISION_PROCESS = {
  "principles": [
    "Courtney & Nick have their Agent licence and can supervise brokers and complete the logs.",
    "Sam & Brynn do not have their branch managers but can be the line managers for their brokers.",
    "Jason (COO) meets with the team leader and the broker and completes the logs for the brokers, with the team leader facilitating the session \u2014 the team leader understands the broker's skill level and can give accurate feedback on what they need to improve on.",
    "All Word documents are kept in the broker's supervision folder and updated at the frequency required by the supervision matrix."
  ],
  "tasks": [
    "Meet with team leaders and explain the process for supervision. Find out what level of experience each broker has and when their last 1:1 supervision meeting was.",
    "At a Thursday meeting, explain to the team the purpose of supervision and why records need updating \u2014 create a slide for this discussion point.",
    "Schedule the first supervision meeting with line managers, broker and JW.",
    "Complete each broker's supervision plan with their capabilities and issues, and update the plan's communication log.",
    "Ask the broker to sign the supervision plan, scan to PDF and file in their personal folder under Supervision."
  ]
};
